import { authLocalization } from "@neondatabase/auth/react"

export const accountLocalization = {
  ...authLocalization,
  ACCEPT: "Godta",
  ACCEPT_INVITATION: "Godta invitasjon",
  ACCEPT_INVITATION_DESCRIPTION: "Du er invitert til aa bli med i en organisasjon.",
  ACCOUNT: "Konto",
  ACCOUNTS: "Kontoer",
  ACCOUNTS_DESCRIPTION: "Bytt mellom kontoene dine.",
  ACCOUNTS_INSTRUCTIONS: "Logg inn med en ekstra konto.",
  ACCOUNT_NOT_FOUND: "Konto ikke funnet",
  ADD_ACCOUNT: "Legg til konto",
  ADD_PASSKEY: "Legg til passkey",
  ADD_TEAM_MEMBER: "Legg til teammedlem",
  ADD_TEAM_MEMBER_SUCCESS: "Teammedlem lagt til",
  ADMIN: "Admin",
  ALREADY_HAVE_AN_ACCOUNT: "Har du allerede en konto?",
  API_KEY: "API-key",
  API_KEYS: "API-keys",
  API_KEYS_DESCRIPTION: "Administrer API-keys for sikker tilgang.",
  API_KEYS_INSTRUCTIONS: "Opprett API-keys for programmatisk tilgang.",
  API_KEY_CREATED: "API-key opprettet",
  API_KEY_NAME_PLACEHOLDER: "Ny API-key",
  APP: "App",
  AVATAR: "Profilbilde",
  AVATAR_DESCRIPTION: "Klikk paa avataren for aa laste opp et bilde.",
  AVATAR_INSTRUCTIONS: "Profilbilde er valgfritt.",
  BACKUP_CODE: "Backup-kode",
  BACKUP_CODES: "Backup-koder",
  BACKUP_CODES_DESCRIPTION: "Lagre kodene trygt. Du kan bruke dem hvis du mister tofaktor.",
  BACKUP_CODES_NOT_ENABLED: "Backup-koder er ikke aktivert",
  BACKUP_CODE_PLACEHOLDER: "Backup-kode",
  BACKUP_CODE_REQUIRED: "Backup-kode er paakrevd",
  BY_CONTINUING_YOU_AGREE: "Ved aa fortsette godtar du",
  CANCEL: "Avbryt",
  CANCEL_INVITATION: "Avbryt invitasjon",
  CHANGE_PASSWORD: "Bytt passord",
  CHANGE_PASSWORD_DESCRIPTION: "Oppdater passordet ditt.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Bruk minst 8 tegn.",
  CHANGE_PASSWORD_SUCCESS: "Passordet er oppdatert.",
  CONFIRM_PASSWORD: "Bekreft passord",
  CONFIRM_PASSWORD_PLACEHOLDER: "Bekreft passord",
  CONFIRM_PASSWORD_REQUIRED: "Bekreft passord er paakrevd",
  CONTINUE: "Fortsett",
  CONTINUE_WITH_AUTHENTICATOR: "Fortsett med autentikator",
  COPIED_TO_CLIPBOARD: "Kopiert",
  COPY_ALL_CODES: "Kopier alle",
  COPY_TO_CLIPBOARD: "Kopier til utklippstavlen",
  CREATE_API_KEY: "Opprett API-key",
  CREATE_API_KEY_DESCRIPTION: "Gi API-key et unikt navn.",
  CREATE_API_KEY_SUCCESS: "Kopier API-key og oppbevar den trygt. Vi kan ikke vise den igjen.",
  CREATE_ORGANIZATION: "Opprett organisasjon",
  CREATE_ORGANIZATION_SUCCESS: "Organisasjon opprettet",
  CREATE_TEAM: "Opprett team",
  CREATE_TEAM_INSTRUCTIONS: "Legg til nytt team i organisasjonen.",
  CREATE_TEAM_SUCCESS: "Team opprettet",
  CURRENT_PASSWORD: "Gjeldende passord",
  CURRENT_PASSWORD_PLACEHOLDER: "Gjeldende passord",
  CURRENT_SESSION: "Aktiv sesjon",
  DELETE: "Slett",
  DELETE_ACCOUNT: "Slett konto",
  DELETE_ACCOUNT_DESCRIPTION: "Slett kontoen din permanent.",
  DELETE_ACCOUNT_INSTRUCTIONS: "Bekreft sletting av kontoen. Dette kan ikke angres.",
  DELETE_ACCOUNT_SUCCESS: "Kontoen din er slettet.",
  DELETE_ACCOUNT_VERIFY: "Sjekk e-posten din for aa bekrefte sletting.",
  DELETE_API_KEY: "Slett API-key",
  DELETE_API_KEY_CONFIRM: "Er du sikker paa at du vil slette denne API-key?",
  DELETE_AVATAR: "Slett bilde",
  DELETE_LOGO: "Slett logo",
  DELETE_ORGANIZATION: "Slett organisasjon",
  DELETE_ORGANIZATION_DESCRIPTION: "Slett organisasjonen permanent.",
  DELETE_ORGANIZATION_INSTRUCTIONS: "Skriv inn organisasjonens slug for aa fortsette:",
  DELETE_ORGANIZATION_SUCCESS: "Organisasjon slettet",
  DELETE_TEAM: "Slett team",
  DELETE_TEAM_DESCRIPTION: "Slett teamet permanent.",
  DELETE_TEAM_INSTRUCTIONS: "Skriv inn teamnavn for aa fortsette:",
  DELETE_TEAM_SUCCESS: "Team slettet",
  DISABLED_CREDENTIALS_DESCRIPTION: "Velg en leverandoer for aa logge inn.",
  DISABLE_TWO_FACTOR: "Deaktiver tofaktor",
  DONE: "Ferdig",
  DONT_HAVE_AN_ACCOUNT: "Har du ikke en konto?",
  EMAIL: "E-post",
  EMAIL_CAN_NOT_BE_UPDATED: "E-post kan ikke oppdateres",
  EMAIL_DESCRIPTION: "Oppdater e-postadressen for kontoen din.",
  EMAIL_INSTRUCTIONS: "Vi sender en bekreftelse ved endring.",
  EMAIL_IS_THE_SAME: "E-postadressen er uendret",
  EMAIL_NOT_VERIFIED: "E-post ikke bekreftet",
  EMAIL_OTP: "E-postkode",
  EMAIL_OTP_DESCRIPTION: "Skriv inn e-posten din for aa motta en kode",
  EMAIL_OTP_SEND_ACTION: "Send kode",
  EMAIL_OTP_VERIFY_ACTION: "Bekreft kode",
  EMAIL_OTP_VERIFICATION_SENT: "Sjekk e-posten din for bekreftelseskoden.",
  EMAIL_PLACEHOLDER: "navn@epost.no",
  EMAIL_REQUIRED: "E-post er paakrevd",
  EMAIL_VERIFICATION: "Bekreftelses-epost er sendt",
  EMAIL_VERIFICATION_REQUIRED: "E-postbekreftelse er paakrevd",
  EMAIL_VERIFY_CHANGE: "Vi sendte en bekreftelse til den nye e-posten.",
  ENABLE_TWO_FACTOR: "Aktiver tofaktor",
  EXPIRES: "Utloper",
  FAILED_TO_CREATE_SESSION: "Kunne ikke opprette sesjon",
  FAILED_TO_CREATE_USER: "Kunne ikke opprette bruker",
  FAILED_TO_GET_SESSION: "Kunne ikke hente sesjon",
  FAILED_TO_GET_USER_INFO: "Kunne ikke hente brukerinfo",
  FAILED_TO_UPDATE_USER: "Kunne ikke oppdatere bruker",
  FORGOT_AUTHENTICATOR: "Glemt autentikator?",
  FORGOT_PASSWORD: "Glemt passord",
  FORGOT_PASSWORD_ACTION: "Send reset-lenke",
  FORGOT_PASSWORD_DESCRIPTION: "Skriv inn e-posten din for aa tilbakestille passordet",
  FORGOT_PASSWORD_EMAIL: "E-post for passordtilbakestilling er sendt",
  FORGOT_PASSWORD_LINK: "Glemt passord?",
  GO_BACK: "Tilbake",
  GUEST: "Gjest",
  INVALID_BACKUP_CODE: "Ugyldig backup-kode",
  INVALID_CODE: "Ugyldig kode",
  INVALID_EMAIL: "Ugyldig e-post",
  INVALID_EMAIL_OR_PASSWORD: "Ugyldig e-post eller passord",
  INVALID_OTP: "Ugyldig kode",
  INVALID_PASSWORD: "Ugyldig passord",
  INVALID_USERNAME: "Ugyldig brukernavn",
  INVALID_USERNAME_OR_PASSWORD: "Ugyldig brukernavn eller passord",
  INVITATION_ACCEPTED: "Invitasjon godtatt",
  INVITATION_CANCELLED: "Invitasjon avbrutt",
  INVITATION_EXPIRED: "Invitasjonen er utlopet",
  INVITATION_REJECTED: "Invitasjon avvist",
  INVITE_MEMBER: "Inviter medlem",
  INVITE_MEMBER_DESCRIPTION: "Send en invitasjon til et nytt medlem.",
  IS_INVALID: "er ugyldig",
  IS_REQUIRED: "er paakrevd",
  IS_THE_SAME: "er uendret",
  LEAVE_ORGANIZATION: "Forlat organisasjon",
  LEAVE_ORGANIZATION_CONFIRM: "Er du sikker paa at du vil forlate organisasjonen?",
  LEAVE_ORGANIZATION_SUCCESS: "Du har forlatt organisasjonen.",
  LINK: "Koble til",
  LOGO: "Logo",
  LOGO_DESCRIPTION: "Klikk paa logoen for aa laste opp et bilde.",
  LOGO_INSTRUCTIONS: "Logo er valgfritt.",
  MAGIC_LINK: "Magic link",
  MAGIC_LINK_ACTION: "Send magic link",
  MAGIC_LINK_DESCRIPTION: "Skriv inn e-posten din for aa motta en magic link",
  MAGIC_LINK_EMAIL: "Sjekk e-posten din for magic link",
  MANAGE_ORGANIZATION: "Administrer organisasjon",
  MANAGE_TEAM_MEMBERS: "Administrer teammedlemmer",
  MANAGE_TEAM_MEMBERS_DESCRIPTION: "Søk og legg til organisasjonsmedlemmer i teamet.",
  MEMBER: "Medlem",
  MEMBERS: "Medlemmer",
  MEMBERS_DESCRIPTION: "Legg til eller fjern medlemmer og roller.",
  MEMBERS_INSTRUCTIONS: "Inviter nye medlemmer til organisasjonen.",
  MEMBER_PLURAL: "medlemmer",
  MEMBER_ROLE_UPDATED: "Medlemsrolle oppdatert",
  MEMBER_SINGULAR: "medlem",
  NAME: "Navn",
  NAME_DESCRIPTION: "Oppdater navnet som vises i profilen din.",
  NAME_INSTRUCTIONS: "Bruk fullt navn.",
  NAME_PLACEHOLDER: "Navn",
  NEVER_EXPIRES: "Utloper aldri",
  NEW_PASSWORD: "Nytt passord",
  NEW_PASSWORD_PLACEHOLDER: "Nytt passord",
  NEW_PASSWORD_REQUIRED: "Nytt passord er paakrevd",
  NO_EXPIRATION: "Ingen utlopsdato",
  NO_TEAMS_FOUND: "Ingen team funnet",
  ONE_TIME_PASSWORD: "Engangskode",
  OPTIONAL_BRACKETS: "(Valgfritt)",
  ORGANIZATION: "Organisasjon",
  ORGANIZATIONS: "Organisasjoner",
  ORGANIZATIONS_DESCRIPTION: "Administrer organisasjoner og medlemskap.",
  ORGANIZATIONS_INSTRUCTIONS: "Opprett en organisasjon for aa samarbeide.",
  ORGANIZATION_NAME: "Navn",
  ORGANIZATION_NAME_DESCRIPTION: "Synlig navn for organisasjonen.",
  ORGANIZATION_NAME_INSTRUCTIONS: "Bruk maks 32 tegn.",
  ORGANIZATION_NAME_PLACEHOLDER: "Acme AS",
  ORGANIZATION_SLUG: "Slug-URL",
  ORGANIZATION_SLUG_DESCRIPTION: "URL-navnerom for organisasjonen.",
  ORGANIZATION_SLUG_INSTRUCTIONS: "Bruk maks 48 tegn.",
  ORGANIZATION_SLUG_PLACEHOLDER: "acme-as",
  OR_CONTINUE_WITH: "Eller fortsett med",
  OTP_EXPIRED: "Koden er utlopet",
  OTP_HAS_EXPIRED: "OTP er utlopet",
  OTP_NOT_ENABLED: "OTP er ikke aktivert",
  OWNER: "Eier",
  PASSKEY: "Passkey",
  PASSKEYS: "Passkeys",
  PASSKEYS_DESCRIPTION: "Administrer passkeys for sikker tilgang.",
  PASSKEYS_INSTRUCTIONS: "Bruk passkeys for aa logge inn uten passord.",
  PASSWORD: "Passord",
  PASSWORDS_DO_NOT_MATCH: "Passordene stemmer ikke",
  PASSWORD_COMPROMISED: "Passordet er kompromittert. Velg et annet passord.",
  PASSWORD_PLACEHOLDER: "Passord",
  PASSWORD_REQUIRED: "Passord er paakrevd",
  PASSWORD_TOO_LONG: "Passordet er for langt",
  PASSWORD_TOO_SHORT: "Passordet er for kort",
  PENDING_INVITATIONS: "Ventende invitasjoner",
  PENDING_INVITATIONS_DESCRIPTION: "Administrer ventende invitasjoner.",
  PENDING_USER_INVITATIONS_DESCRIPTION: "Invitasjoner du har mottatt.",
  PERSONAL_ACCOUNT: "Personlig konto",
  PRIVACY_POLICY: "Personvern",
  PROTECTED_BY_RECAPTCHA: "Denne siden er beskyttet av reCAPTCHA.",
  PROVIDERS: "Leverandoerer",
  PROVIDERS_DESCRIPTION: "Koble kontoen din til tredjepart.",
  RECOVER_ACCOUNT: "Gjenopprett konto",
  RECOVER_ACCOUNT_ACTION: "Gjenopprett konto",
  RECOVER_ACCOUNT_DESCRIPTION: "Skriv inn en backup-kode for aa faa tilgang",
  REJECT: "Avvis",
  REMEMBER_ME: "Husk meg",
  REMOVE: "Fjern",
  REMOVE_MEMBER: "Fjern medlem",
  REMOVE_MEMBER_CONFIRM: "Er du sikker paa at du vil fjerne dette medlemmet?",
  REMOVE_MEMBER_SUCCESS: "Medlem fjernet",
  REMOVE_TEAM_CONFIRM: "Er du sikker paa at du vil fjerne dette teamet?",
  REMOVE_TEAM_MEMBER: "Fjern teammedlem",
  REMOVE_TEAM_MEMBER_CONFIRM: "Er du sikker paa at du vil fjerne dette teammedlemmet?",
  REMOVE_TEAM_MEMBER_SUCCESS: "Teammedlem fjernet",
  REQUEST_FAILED: "Foresporsel feilet",
  RESEND_CODE: "Send kode paa nytt",
  RESEND_VERIFICATION_EMAIL: "Send ny bekreftelse",
  RESET_PASSWORD: "Tilbakestill passord",
  RESET_PASSWORD_ACTION: "Lagre nytt passord",
  RESET_PASSWORD_DESCRIPTION: "Skriv inn nytt passord under",
  RESET_PASSWORD_SUCCESS: "Passord tilbakestilt",
  REVOKE: "Fjern",
  ROLE: "Rolle",
  SAVE: "Lagre",
  SECURITY: "Sikkerhet",
  SELECT_ROLE: "Velg rolle",
  SEND_INVITATION: "Send invitasjon",
  SEND_INVITATION_SUCCESS: "Invitasjon sendt",
  SEND_VERIFICATION_CODE: "Send bekreftelseskode",
  SESSIONS: "Sesjoner",
  SESSIONS_DESCRIPTION: "Administrer aktive innlogginger.",
  SESSION_EXPIRED: "Sesjonen er utlopet. Logg inn paa nytt.",
  SESSION_NOT_FRESH: "Sesjonen din er ikke fersk. Logg inn paa nytt.",
  SETTINGS: "Innstillinger",
  SET_PASSWORD: "Sett passord",
  SET_PASSWORD_DESCRIPTION: "Klikk knappen for aa motta en e-post for aa sette passord.",
  SIGN_IN: "Logg inn",
  SIGN_IN_ACTION: "Logg inn",
  SIGN_IN_DESCRIPTION: "Skriv inn e-posten din for aa logge inn",
  SIGN_IN_USERNAME_DESCRIPTION: "Skriv inn brukernavn eller e-post for aa logge inn",
  SIGN_IN_USERNAME_PLACEHOLDER: "Brukernavn eller e-post",
  SIGN_IN_WITH: "Logg inn med",
  SIGN_OUT: "Logg ut",
  SIGN_UP: "Registrer deg",
  SIGN_UP_ACTION: "Opprett konto",
  SIGN_UP_DESCRIPTION: "Skriv inn informasjonen din for aa opprette konto",
  SIGN_UP_EMAIL: "Sjekk e-posten din for bekreftelseslenken.",
  SLUG_DOES_NOT_MATCH: "Slug stemmer ikke",
  SLUG_REQUIRED: "Slug er paakrevd",
  SWITCH_ACCOUNT: "Bytt konto",
  TEAM: "Team",
  TEAMS: "Team",
  TEAMS_DESCRIPTION: "Administrer team i organisasjonen.",
  TEAM_ACTIVE: "Aktivt",
  TEAM_MEMBERS: "Teammedlemmer",
  TEAM_MEMBERS_DESCRIPTION: "Administrer teammedlemmer og roller.",
  TEAM_NAME: "Teamnavn",
  TEAM_NAME_DESCRIPTION: "Synlig navn for teamet.",
  TEAM_NAME_INSTRUCTIONS: "Bruk maks 64 tegn.",
  TEAM_NAME_PLACEHOLDER: "Produktteam",
  TEAM_NAME_REQUIRED: "Teamnavn er paakrevd",
  TEAM_NAME_DOES_NOT_MATCH: "Teamnavn stemmer ikke",
  TEAM_SET_ACTIVE: "Sett aktiv",
  TERMS_OF_SERVICE: "Vilkaar",
  TOO_MANY_ATTEMPTS: "For mange forsøk",
  TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "For mange forsøk. Be om en ny kode.",
  TOTP_NOT_ENABLED: "TOTP er ikke aktivert",
  TRUST_DEVICE: "Stol paa denne enheten",
  TWO_FACTOR: "Tofaktor",
  TWO_FACTOR_ACTION: "Bekreft kode",
  TWO_FACTOR_CARD_DESCRIPTION: "Legg til et ekstra sikkerhetslag.",
  TWO_FACTOR_DESCRIPTION: "Skriv inn engangskoden for aa fortsette",
  TWO_FACTOR_DISABLED: "Tofaktor er deaktivert",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Skriv inn passordet ditt for aa deaktivere 2FA.",
  TWO_FACTOR_ENABLED: "Tofaktor er aktivert",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Skriv inn passordet ditt for aa aktivere 2FA.",
  TWO_FACTOR_NOT_ENABLED: "Tofaktor er ikke aktivert",
  TWO_FACTOR_PROMPT: "Tofaktor-autentisering",
  TWO_FACTOR_TOTP_LABEL: "Skann QR-koden med autentikator",
  UNLINK: "Koble fra",
  UNKNOWN: "Ukjent",
  UPDATE: "Oppdater",
  UPDATED_SUCCESSFULLY: "oppdatert",
  UPDATE_ROLE: "Oppdater rolle",
  UPDATE_ROLE_DESCRIPTION: "Oppdater rollen til medlemmet",
  UPDATE_TEAM: "Oppdater team",
  UPDATE_TEAM_DESCRIPTION: "Oppdater teamnavn",
  UPDATE_TEAM_SUCCESS: "Team oppdatert",
  UPLOAD: "Last opp",
  UPLOAD_AVATAR: "Last opp bilde",
  UPLOAD_LOGO: "Last opp logo",
  USER: "Bruker",
  USERNAME: "Brukernavn",
  USERNAME_DESCRIPTION: "Oppdater brukernavnet ditt.",
  USERNAME_INSTRUCTIONS: "Bruk 3-32 tegn.",
  USERNAME_IS_ALREADY_TAKEN: "Brukernavnet er allerede tatt",
  USERNAME_PLACEHOLDER: "Brukernavn",
  USERNAME_TOO_LONG: "Brukernavnet er for langt",
  USERNAME_TOO_SHORT: "Brukernavnet er for kort",
  USER_ALREADY_EXISTS: "Bruker finnes allerede",
  USER_ALREADY_HAS_PASSWORD: "Brukeren har allerede passord. Oppgi det for aa slette kontoen.",
  USER_NOT_FOUND: "Bruker ikke funnet",
  USER_TEAMS_DESCRIPTION: "Du er medlem av folgende team.",
  VERIFY_YOUR_EMAIL: "Bekreft e-post",
  VERIFY_YOUR_EMAIL_DESCRIPTION: "Bekreft e-posten din for full tilgang.",
} as const
